# GitSage GoReleaser Configuration
# https://goreleaser.com

# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

project_name: gitsage

# Hooks to run before building
before:
  hooks:
    - go mod tidy
    - go generate ./...

# Build configuration
builds:
  - id: gitsage
    main: ./cmd/gitsage
    binary: gitsage
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    # Exclude Windows arm64 (not commonly used)
    ignore:
      - goos: windows
        goarch: arm64
    # Version injection via ldflags
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    # Build flags
    flags:
      - -trimpath
    # Mod timestamp for reproducible builds
    mod_timestamp: "{{ .CommitTimestamp }}"

# Archive configuration
archives:
  - id: default
    format: tar.gz
    # Use zip for Windows
    format_overrides:
      - goos: windows
        format: zip
    # Archive naming template
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    # Files to include in archive
    files:
      - README.md
      - LICENSE*
      - CHANGELOG*

# Checksum configuration
checksum:
  name_template: "checksums.txt"
  algorithm: sha256

# Snapshot configuration (for non-tagged builds)
snapshot:
  version_template: "{{ incpatch .Version }}-next"

# Changelog configuration
changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"
      - "^style:"
      - Merge pull request
      - Merge branch
  groups:
    - title: "🚀 Features"
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "🐛 Bug Fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "📚 Documentation"
      regexp: '^.*?docs(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: "🔧 Maintenance"
      order: 999

# Release configuration
release:
  github:
    owner: gitsage
    name: gitsage
  # Draft release for review before publishing
  draft: false
  # Mark as prerelease if version contains alpha/beta/rc
  prerelease: auto
  # Release name template
  name_template: "GitSage v{{.Version}}"
  # Release header
  header: |
    ## GitSage v{{.Version}}
    
    AI-powered git commit message generator.
  # Release footer
  footer: |
    ---
    
    **Full Changelog**: https://github.com/gitsage/gitsage/compare/{{ .PreviousTag }}...{{ .Tag }}
    
    ## Installation
    
    ### Using Go
    ```bash
    go install github.com/gitsage/gitsage@v{{.Version}}
    ```
    
    ### Download Binary
    Download the appropriate binary for your platform from the assets below.

# Source archive
source:
  enabled: true
  name_template: "{{ .ProjectName }}_{{ .Version }}_source"

# SBOM (Software Bill of Materials)
sboms:
  - artifacts: archive

# Signing (optional - uncomment to enable)
# signs:
#   - artifacts: checksum
#     cmd: gpg
#     args:
#       - "--batch"
#       - "-u"
#       - "{{ .Env.GPG_FINGERPRINT }}"
#       - "--output"
#       - "${signature}"
#       - "--detach-sign"
#       - "${artifact}"

# Announce (optional - uncomment to enable)
# announce:
#   discord:
#     enabled: true
#     message_template: "GitSage {{ .Tag }} is out! Check it out: {{ .ReleaseURL }}"
